### ISSUE TITLE
Beginner's consultation

### ISSUE THREAD

**Issue by zy358008500** [csheaff/pa-tomography-xu-wang#2]
@csheaff Hello! I am a beginner of python, it is an honor to see your code. Want to ask you a few questions: (1) how to draw the initial sound pressure signal? (2) how to draw the initial sound pressure curve, as in the literature?
Looking forward to your reply，Thank you！

**Comment by csheaff** [comment]
Hi, thanks for the interest. The easiest thing to do is probably to run this in an Ipython terminal so that it imports all the functions and variables from main in the namespace. So from Ipython console, do:

`%run pa_tom_sim.py`

You can then look at the functions and variables available with `%whos` command.

One of the variables is "sigs" which contain all the signals recorded by the each array sub-element. To plot one of these signals you can run:

`plt.plot(sigs[:, 45, 45]); plt.show()`

Note a Hanning filter is applied in getSignals() to simulate the finite bandwidth of the transducers. If you wanted to see the unfiltered signals you could comment out that line and re-run. 

Hope this helps.

**Comment by zy358008500** [comment]
Thank you very much for your answer！ You are the first time I have received a reply in Github. This made me see the hope of learning Python.

I've studied your published "us-beamform-linarray" , which uses Matlab toolbox K-wave.The images from the experiment excited me.And I found out that there's an example in the K-wave called "example_pr_3D_FFT_planar_sensor.m" that looks like "pa-tomography".

So,I want to do an experiment: use the photoacoustic signal collected by the detector in "example_pr_3D_FFT_planar_sensor.m" , and then reconstruct it in "pa-tomography".In other words,"senser_data_rs.mat"  instead of  "prec[:, xi, yi]".But my programming skills don't support my ideas.I sincerely hope for your help  in future. 

Thank you again for your reply.
 
![image](https://user-images.githubusercontent.com/46587789/55804141-537ecf00-5b0e-11e9-8cdd-df2d4a0aa9eb.png)
![image](https://user-images.githubusercontent.com/46587789/55804166-5e396400-5b0e-11e9-8fdd-523419a9c3cf.png)

**Comment by zy358008500** [comment]
Hello！I've been learning your code, and there are still some questions I'd like to ask you.
1.#desired spatial resolution (m),How to determine Resolution?
2.I replaced the prec in the code with the data detected in Matlab,It turns out wrong: 

> index 215 is out of bounds for axis 0 with size 212

what's going on? Thank You!

**Comment by csheaff** [comment]
1. The "desired spatial resolution" refers to the grid size - in other words, it is the smallest dimension that can be represented by the simulation. The resolution of the target reconstruction will depend on several factors, and you can find this information in ultrasound literature. Lateral resolution is dependent on the aperture size, wavelength, and depth. So to get better lateral resolution you could make the array larger, increase the bandwidth of the detectors (increase fc), and move the targets closer. Axial resolution depends on the bandwidth of the detectors. So increasing fc should also improve axial resolution.

Note that you may need to increase the sampling frequency (fs) in order to represent higher frequencies, and this will slow down the simulation.

2. It is hard to say. My guess is that you are not indexing the correct dimension. Watch out for how .mat files are imported with scipy. Sometimes they add another dimension, and using np.squeeze() can be used to eliminate it.

**Comment by zy358008500** [comment]
Thank you very much for your reply.
1. l found that lowering the spatial resolution did make the reconstructed image more delicate.I'll see more about the literature.
2. I found that the length of the last dimension of .mat is 212.  I tried to change 
`b1 = b[distind - 1]`  to `b1 = b[distind - 50]` , and the error disappeared. But I still don't know what the real reason is.
Thank you again for your guidance. I will continue my efforts.
